### ISSUE TITLE
Fix Please

### ISSUE THREAD

**Issue by lczacktd** [Lcjacobpd/dungeon-manager#1]
Set monster/player health to 0 automatically when status is set to "dead".
Remove all the code pertaining to whitespace; creates issues with multi-word monster names.
Consider using monster IDs instead of searching via name.
help me get friends

**Comment by Lcjacobpd** [comment]
All issues apart from implementing a monster ID system, resolved in latest push "Admit You Died".
You'll also find that setting a creature's HP to 0 will also mark it as dead. (update is bidirectional).
Thank you for your input!
